// Generated by GitHub Copilot
package com.habittracker.dto;

import jakarta.validation.constraints.Min;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Transfer Object for creating or updating a Daily Expense record.
 * Used for API request validation.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyExpenseDTO {

    private LocalDate entryDate;

    @Min(value = 0, message = "Need amount cannot be negative")
    private Double needAmount = 0.0;

    @Min(value = 0, message = "Want amount cannot be negative")
    private Double wantAmount = 0.0;

    private List<String> wantCategories = new ArrayList<>();
}
