// Generated by GitHub Copilot
package com.habittracker.dto;

import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Data Transfer Object for creating or updating a Habit Entry.
 * Used for API request validation.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class HabitEntryDTO {

    private Long id;

    @NotNull(message = "Habit ID is required")
    private Long habitId;

    private LocalDate entryDate;

    private Boolean completed = false;

    private String notes;
}
