// Generated by GitHub Copilot
package com.habittracker.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for creating or updating a Habit.
 * Used for API request validation.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class HabitDTO {

    private Long id;

    @NotBlank(message = "Habit name is required")
    @Size(min = 2, max = 100, message = "Habit name must be between 2 and 100 characters")
    private String name;

    @Size(max = 500, message = "Description cannot exceed 500 characters")
    private String description;

    private String frequency = "daily";

    private Integer targetCount = 1;

    private Boolean isActive = true;
}
