// Generated by GitHub Copilot
package com.habittracker.service;

import com.habittracker.dto.DailyExpenseDTO;
import com.habittracker.entity.DailyExpense;
import com.habittracker.repository.DailyExpenseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

/**
 * Service class for managing Daily Expense operations.
 * Implements business logic for need/want expense tracking.
 */
@Service
@Transactional
public class DailyExpenseService {

    @Autowired
    private DailyExpenseRepository dailyExpenseRepository;

    /**
     * Retrieve the expense record for a specific date.
     * @param entryDate The entry date
     * @return The expense record, or null if none exists for that date
     */
    public DailyExpense getByDate(LocalDate entryDate) {
        return dailyExpenseRepository.findByEntryDate(entryDate).orElse(null);
    }

    /**
     * Retrieve expense records within a date range.
     * @param startDate Start date
     * @param endDate End date
     * @return List of expense records
     */
    public List<DailyExpense> getByDateRange(LocalDate startDate, LocalDate endDate) {
        return dailyExpenseRepository.findByEntryDateBetween(startDate, endDate);
    }

    /**
     * Create or update the expense record for a date.
     * Security note: Numeric bounds are validated via @Min on the DTO before reaching here.
     * @param dailyExpenseDTO The expense data
     * @return The created or updated expense record
     */
    public DailyExpense createOrUpdateExpense(DailyExpenseDTO dailyExpenseDTO) {
        LocalDate entryDate = dailyExpenseDTO.getEntryDate() != null
                ? dailyExpenseDTO.getEntryDate()
                : LocalDate.now();

        return dailyExpenseRepository.findByEntryDate(entryDate)
                .map(existing -> {
                    existing.setNeedAmount(dailyExpenseDTO.getNeedAmount());
                    existing.setWantAmount(dailyExpenseDTO.getWantAmount());
                    existing.setWantCategories(dailyExpenseDTO.getWantCategories());
                    return dailyExpenseRepository.save(existing);
                })
                .orElseGet(() -> {
                    DailyExpense newExpense = new DailyExpense();
                    newExpense.setEntryDate(entryDate);
                    newExpense.setNeedAmount(dailyExpenseDTO.getNeedAmount());
                    newExpense.setWantAmount(dailyExpenseDTO.getWantAmount());
                    newExpense.setWantCategories(dailyExpenseDTO.getWantCategories());
                    return dailyExpenseRepository.save(newExpense);
                });
    }
}
