// Generated by GitHub Copilot
package com.habittracker.service;

import com.habittracker.dto.HabitEntryDTO;
import com.habittracker.entity.Habit;
import com.habittracker.entity.HabitEntry;
import com.habittracker.repository.HabitEntryRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

/**
 * Service class for managing Habit Entry operations.
 * Implements business logic for habit completion tracking.
 */
@Service
@Transactional
public class HabitEntryService {

    @Autowired
    private HabitEntryRepository habitEntryRepository;

    @Autowired
    private HabitService habitService;

    /**
     * Retrieve all entries for a specific habit.
     * @param habitId The habit ID
     * @return List of habit entries
     */
    public List<HabitEntry> getEntriesByHabitId(Long habitId) {
        return habitEntryRepository.findByHabitId(habitId);
    }

    /**
     * Retrieve entries for a habit within a date range.
     * @param habitId The habit ID
     * @param startDate Start date
     * @param endDate End date
     * @return List of habit entries
     */
    public List<HabitEntry> getEntriesByDateRange(Long habitId, LocalDate startDate, LocalDate endDate) {
        return habitEntryRepository.findByHabitIdAndEntryDateBetween(habitId, startDate, endDate);
    }

    /**
     * Create or update a habit entry.
     * Security note: Validates habit existence before creating entry.
     * @param habitEntryDTO The entry data
     * @return The created or updated entry
     */
    public HabitEntry createOrUpdateEntry(HabitEntryDTO habitEntryDTO) {
        Habit habit = habitService.getHabitById(habitEntryDTO.getHabitId());
        if (habit == null) {
            throw new RuntimeException("Habit not found with id: " + habitEntryDTO.getHabitId());
        }
        
        LocalDate entryDate = habitEntryDTO.getEntryDate() != null 
                ? habitEntryDTO.getEntryDate() 
                : LocalDate.now();

        // Check if entry already exists for this date
        return habitEntryRepository.findByHabitIdAndEntryDate(habitEntryDTO.getHabitId(), entryDate)
                .map(existingEntry -> {
                    existingEntry.setCompleted(habitEntryDTO.getCompleted());
                    existingEntry.setNotes(habitEntryDTO.getNotes());
                    return habitEntryRepository.save(existingEntry);
                })
                .orElseGet(() -> {
                    HabitEntry newEntry = new HabitEntry();
                    newEntry.setHabit(habit);
                    newEntry.setEntryDate(entryDate);
                    newEntry.setCompleted(habitEntryDTO.getCompleted());
                    newEntry.setNotes(habitEntryDTO.getNotes());
                    return habitEntryRepository.save(newEntry);
                });
    }

    /**
     * Delete a habit entry.
     * Security note: Validates entry exists before deletion.
     * @param id The entry ID
     * @throws RuntimeException if entry not found
     */
    public void deleteEntry(Long id) {
        HabitEntry entry = habitEntryRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Habit entry not found with id: " + id));
        habitEntryRepository.delete(entry);
    }
}
