// Generated by GitHub Copilot
package com.habittracker.service;

import com.habittracker.dto.HabitDTO;
import com.habittracker.entity.Habit;
import com.habittracker.repository.HabitRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Service class for managing Habit operations.
 * Implements business logic for habit tracking.
 */
@Service
@Transactional
public class HabitService {

    @Autowired
    private HabitRepository habitRepository;

    /**
     * Retrieve all habits.
     * @return List of all habits
     */
    public List<Habit> getAllHabits() {
        return habitRepository.findAll();
    }

    /**
     * Retrieve all active habits.
     * @return List of active habits
     */
    public List<Habit> getActiveHabits() {
        return habitRepository.findByIsActiveTrue();
    }

    /**
     * Retrieve a habit by ID.
     * @param id The habit ID
     * @return The habit
     * @throws RuntimeException if habit not found
     */
    public Habit getHabitById(Long id) {
        return habitRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Habit not found with id: " + id));
    }

    /**
     * Create a new habit.
     * @param habitDTO The habit data
     * @return The created habit
     */
    public Habit createHabit(HabitDTO habitDTO) {
        Habit habit = new Habit();
        habit.setName(habitDTO.getName());
        habit.setDescription(habitDTO.getDescription());
        habit.setFrequency(habitDTO.getFrequency());
        habit.setTargetCount(habitDTO.getTargetCount());
        habit.setIsActive(habitDTO.getIsActive());
        return habitRepository.save(habit);
    }

    /**
     * Update an existing habit.
     * @param id The habit ID
     * @param habitDTO The updated habit data
     * @return The updated habit
     * @throws RuntimeException if habit not found
     */
    public Habit updateHabit(Long id, HabitDTO habitDTO) {
        Habit habit = getHabitById(id);
        habit.setName(habitDTO.getName());
        habit.setDescription(habitDTO.getDescription());
        habit.setFrequency(habitDTO.getFrequency());
        habit.setTargetCount(habitDTO.getTargetCount());
        habit.setIsActive(habitDTO.getIsActive());
        return habitRepository.save(habit);
    }

    /**
     * Delete a habit.
     * Security note: Validates habit exists before deletion.
     * @param id The habit ID
     * @throws RuntimeException if habit not found
     */
    public void deleteHabit(Long id) {
        Habit habit = getHabitById(id);
        habitRepository.delete(habit);
    }

    /**
     * Search habits by name.
     * @param name Search term
     * @return List of matching habits
     */
    public List<Habit> searchHabitsByName(String name) {
        return habitRepository.findByNameContainingIgnoreCase(name);
    }
}
