import React, { useState, useEffect, useRef, useCallback } from 'react';
import ExpenseService from '../services/ExpenseService';
import '../styles/ExpenseTracker.css';

// Generated by GitHub Copilot - Sep-19-2026
const WANT_CATEGORIES = ['Travel', 'Fuel', 'Fun'];
const SAVE_DEBOUNCE_MS = 600;

const ExpenseTracker = () => {
    const today = new Date();
    const dateKey = today.toISOString().split('T')[0];

    const [needExpense, setNeedExpense] = useState('');
    const [wantExpense, setWantExpense] = useState('');
    const [wantCategories, setWantCategories] = useState([]);
    const [loading, setLoading] = useState(true);
    const saveTimeoutRef = useRef(null);

    useEffect(() => {
        let isMounted = true;

        ExpenseService.getByDate(dateKey)
            .then((response) => {
                if (isMounted && response.data) {
                    setNeedExpense(response.data.needAmount ? String(response.data.needAmount) : '');
                    setWantExpense(response.data.wantAmount ? String(response.data.wantAmount) : '');
                    setWantCategories(response.data.wantCategories || []);
                }
            })
            .catch((error) => console.error('Error loading expense for today:', error))
            .finally(() => {
                if (isMounted) {
                    setLoading(false);
                }
            });

        return () => {
            isMounted = false;
            if (saveTimeoutRef.current) {
                clearTimeout(saveTimeoutRef.current);
            }
        };
    }, [dateKey]);

    /**
     * Persist the current Need/Want state to the backend, debounced so a
     * request isn't fired on every keystroke.
     */
    const scheduleSave = useCallback((nextNeed, nextWant, nextCategories) => {
        if (saveTimeoutRef.current) {
            clearTimeout(saveTimeoutRef.current);
        }

        saveTimeoutRef.current = setTimeout(() => {
            ExpenseService.createOrUpdateExpense({
                entryDate: dateKey,
                needAmount: parseFloat(nextNeed) || 0,
                wantAmount: parseFloat(nextWant) || 0,
                wantCategories: nextCategories
            }).catch((error) => console.error('Error saving expense:', error));
        }, SAVE_DEBOUNCE_MS);
    }, [dateKey]);

    const handleNeedExpenseChange = (event) => {
        const value = event.target.value;
        setNeedExpense(value);
        scheduleSave(value, wantExpense, wantCategories);
    };

    const handleWantExpenseChange = (event) => {
        const value = event.target.value;
        setWantExpense(value);
        scheduleSave(needExpense, value, wantCategories);
    };

    const handleWantCategoryToggle = (category) => {
        const updated = wantCategories.includes(category)
            ? wantCategories.filter((item) => item !== category)
            : [...wantCategories, category];

        setWantCategories(updated);
        scheduleSave(needExpense, wantExpense, updated);
    };

    const formattedDate = today.toLocaleDateString('en-GB', {
        day: '2-digit',
        month: 'long',
        year: 'numeric'
    });

    const totalExpense = (parseFloat(needExpense) || 0) + (parseFloat(wantExpense) || 0);

    if (loading) {
        return (
            <section className="expense-tracker" aria-labelledby="expense-tracker-label">
                <p>Loading today's expense...</p>
            </section>
        );
    }

    return (
        <section className="expense-tracker" aria-labelledby="expense-tracker-label">
            <label id="expense-tracker-label" htmlFor="need-expense">
                {formattedDate}
            </label>
            <div className="expense-total" aria-live="polite">
                <span className="expense-total-label">Total</span>
                <span className="expense-total-value">{totalExpense.toFixed(2)}</span>
            </div>
            <div className="expense-tracker-columns">
                <div className="expense-column">
                    <label htmlFor="need-expense">Need</label>
                    <input
                        id="need-expense"
                        type="number"
                        min="0"
                        step="0.01"
                        inputMode="decimal"
                        value={needExpense}
                        onChange={handleNeedExpenseChange}
                        placeholder="Enter need expense"
                    />
                </div>
                <div className="expense-column">
                    <label htmlFor="want-expense">Want</label>
                    <input
                        id="want-expense"
                        type="number"
                        min="0"
                        step="0.01"
                        inputMode="decimal"
                        value={wantExpense}
                        onChange={handleWantExpenseChange}
                        placeholder="Enter want expense"
                    />
                    <fieldset className="want-categories">
                        <legend>Spent on</legend>
                        {WANT_CATEGORIES.map((category) => {
                            const checkboxId = `want-category-${category.toLowerCase()}`;
                            return (
                                <div className="want-category-item" key={category}>
                                    <input
                                        id={checkboxId}
                                        type="checkbox"
                                        checked={wantCategories.includes(category)}
                                        onChange={() => handleWantCategoryToggle(category)}
                                    />
                                    <label htmlFor={checkboxId}>{category}</label>
                                </div>
                            );
                        })}
                    </fieldset>
                </div>
            </div>
        </section>
    );
};

export default ExpenseTracker;