import React, { useState } from 'react';
import '../styles/ExpenseTracker.css';

// Generated by GitHub Copilot - Sep-19-2026
const WANT_CATEGORIES = ['Travel', 'Fuel', 'Fun'];

const ExpenseTracker = () => {
    const today = new Date();
    const dateKey = today.toISOString().split('T')[0];
    const needStorageKey = `daily-expense-need-${dateKey}`;
    const wantStorageKey = `daily-expense-want-${dateKey}`;
    const wantCategoriesStorageKey = `daily-expense-want-categories-${dateKey}`;

    const [needExpense, setNeedExpense] = useState(() => localStorage.getItem(needStorageKey) || '');
    const [wantExpense, setWantExpense] = useState(() => localStorage.getItem(wantStorageKey) || '');
    const [wantCategories, setWantCategories] = useState(() => {
        const stored = localStorage.getItem(wantCategoriesStorageKey);
        return stored ? JSON.parse(stored) : [];
    });

    const handleNeedExpenseChange = (event) => {
        const value = event.target.value;
        setNeedExpense(value);

        if (value) {
            localStorage.setItem(needStorageKey, value);
        } else {
            localStorage.removeItem(needStorageKey);
        }
    };

    const handleWantExpenseChange = (event) => {
        const value = event.target.value;
        setWantExpense(value);

        if (value) {
            localStorage.setItem(wantStorageKey, value);
        } else {
            localStorage.removeItem(wantStorageKey);
        }
    };

    const handleWantCategoryToggle = (category) => {
        const updated = wantCategories.includes(category)
            ? wantCategories.filter((item) => item !== category)
            : [...wantCategories, category];

        setWantCategories(updated);

        if (updated.length) {
            localStorage.setItem(wantCategoriesStorageKey, JSON.stringify(updated));
        } else {
            localStorage.removeItem(wantCategoriesStorageKey);
        }
    };

    const formattedDate = today.toLocaleDateString('en-GB', {
        day: '2-digit',
        month: 'long',
        year: 'numeric'
    });

    const totalExpense = (parseFloat(needExpense) || 0) + (parseFloat(wantExpense) || 0);

    return (
        <section className="expense-tracker" aria-labelledby="expense-tracker-label">
            <label id="expense-tracker-label" htmlFor="need-expense">
                {formattedDate}
            </label>
            <div className="expense-total" aria-live="polite">
                <span className="expense-total-label">Total</span>
                <span className="expense-total-value">{totalExpense.toFixed(2)}</span>
            </div>
            <div className="expense-tracker-columns">
                <div className="expense-column">
                    <label htmlFor="need-expense">Need</label>
                    <input
                        id="need-expense"
                        type="number"
                        min="0"
                        step="0.01"
                        inputMode="decimal"
                        value={needExpense}
                        onChange={handleNeedExpenseChange}
                        placeholder="Enter need expense"
                    />
                </div>
                <div className="expense-column">
                    <label htmlFor="want-expense">Want</label>
                    <input
                        id="want-expense"
                        type="number"
                        min="0"
                        step="0.01"
                        inputMode="decimal"
                        value={wantExpense}
                        onChange={handleWantExpenseChange}
                        placeholder="Enter want expense"
                    />
                    <fieldset className="want-categories">
                        <legend>Spent on</legend>
                        {WANT_CATEGORIES.map((category) => {
                            const checkboxId = `want-category-${category.toLowerCase()}`;
                            return (
                                <div className="want-category-item" key={category}>
                                    <input
                                        id={checkboxId}
                                        type="checkbox"
                                        checked={wantCategories.includes(category)}
                                        onChange={() => handleWantCategoryToggle(category)}
                                    />
                                    <label htmlFor={checkboxId}>{category}</label>
                                </div>
                            );
                        })}
                    </fieldset>
                </div>
            </div>
        </section>
    );
};

export default ExpenseTracker;