/* Generated by GitHub Copilot */
import React, { useState, useEffect } from 'react';
import HabitService from '../services/HabitService';
import HabitEntryService from '../services/HabitEntryService';
import DailyTracker from './DailyTracker';
import '../styles/HabitList.css';

/**
 * Component to display and manage the list of habits.
 * Accessible: Uses semantic HTML and keyboard navigation.
 */
const HabitList = () => {
    const [habits, setHabits] = useState([]);
    const [completedToday, setCompletedToday] = useState({});
    const [showForm, setShowForm] = useState(false);
    const [editingHabit, setEditingHabit] = useState(null);
    const [refreshTrigger, setRefreshTrigger] = useState(0);
    const [formData, setFormData] = useState({
        name: '',
        description: '',
        frequency: 'daily',
        targetCount: 1,
        isActive: true
    });

    useEffect(() => {
        loadHabits();
    }, []);

    /**
     * Load all habits from the backend and check today's completion status.
     * Efficient: Minimizes API calls by loading once on mount.
     */
    const loadHabits = () => {
        const today = new Date().toISOString().split('T')[0];
        
        HabitService.getAllHabits()
            .then(response => {
                const allHabits = response.data;
                setHabits(allHabits);
                
                // Check completion status for each habit for today
                const completionPromises = allHabits.map(habit =>
                    HabitEntryService.getEntriesByDateRange(habit.id, today, today)
                        .then(entriesResponse => {
                            const todayEntry = entriesResponse.data.find(
                                entry => entry.entryDate === today && entry.completed
                            );
                            return { habitId: habit.id, completed: !!todayEntry };
                        })
                        .catch(() => ({ habitId: habit.id, completed: false }))
                );

                return Promise.all(completionPromises);
            })
            .then(completionStatuses => {
                const completedMap = {};
                completionStatuses.forEach(status => {
                    if (status.completed) {
                        completedMap[status.habitId] = true;
                    }
                });
                setCompletedToday(completedMap);
            })
            .catch(error => {
                console.error('Error loading habits:', error);
            });
    };

    /**
     * Handle form input changes.
     * @param {Event} e - Input change event
     */
    const handleInputChange = (e) => {
        const { name, value, type, checked } = e.target;
        setFormData({
            ...formData,
            [name]: type === 'checkbox' ? checked : value
        });
    };

    /**
     * Submit habit form (create or update).
     * Security: Data validated on backend via Spring validation.
     * @param {Event} e - Form submit event
     */
    const handleSubmit = (e) => {
        e.preventDefault();
        
        const habitData = {
            ...formData,
            targetCount: parseInt(formData.targetCount)
        };

        if (editingHabit) {
            HabitService.updateHabit(editingHabit.id, habitData)
                .then(() => {
                    loadHabits();
                    resetForm();
                })
                .catch(error => console.error('Error updating habit:', error));
        } else {
            HabitService.createHabit(habitData)
                .then(() => {
                    loadHabits();
                    resetForm();
                })
                .catch(error => console.error('Error creating habit:', error));
        }
    };

    /**
     * Load habit data into form for editing.
     * @param {Object} habit - The habit to edit
     */
    const handleEdit = (habit) => {
        setEditingHabit(habit);
        setFormData({
            name: habit.name,
            description: habit.description || '',
            frequency: habit.frequency,
            targetCount: habit.targetCount,
            isActive: habit.isActive
        });
        setShowForm(true);
    };

    /**
     * Delete a habit.
     * @param {number} id - The habit ID
     */
    const handleDelete = (id) => {
        if (window.confirm('Are you sure you want to delete this habit?')) {
            HabitService.deleteHabit(id)
                .then(() => loadHabits())
                .catch(error => console.error('Error deleting habit:', error));
        }
    };

    /**
     * Toggle habit completion for today.
     * @param {number} habitId - The habit ID
     */
    const toggleCompletion = (habitId) => {
        const today = new Date().toISOString().split('T')[0];
        HabitEntryService.createOrUpdateEntry({
            habitId: habitId,
            entryDate: today,
            completed: true
        })
        .then(() => {
        setCompletedToday(prev => ({
            ...prev,
            [habitId]: true
        }));
        // Trigger DailyTracker refresh
        setRefreshTrigger(prev => prev + 1);
    })
        .catch(error => console.error('Error updating entry:', error));
    };

    /**
     * Reset form to initial state.
     */
    const resetForm = () => {
        setFormData({
            name: '',
            description: '',
            frequency: 'daily',
            targetCount: 1,
            isActive: true
        });
        setEditingHabit(null);
        setShowForm(false);
    };

    return (
        <div className="habit-list-container">
            <div className="habit-content-wrapper">
                <div className="habit-main-section">
                    <div className="page-header">
                        <h2>My Habits</h2>
                        <button 
                            onClick={() => setShowForm(!showForm)}
                            className="btn-primary"
                            aria-label="Add new habit"
                        >
                            {showForm ? 'Cancel' : 'Add Habit'}
                        </button>
                    </div>

            {showForm && (
                <form onSubmit={handleSubmit} className="habit-form">
                    <h2>{editingHabit ? 'Edit Habit' : 'New Habit'}</h2>
                    
                    <div className="form-group">
                        <label htmlFor="name">Habit Name *</label>
                        <input
                            type="text"
                            id="name"
                            name="name"
                            value={formData.name}
                            onChange={handleInputChange}
                            required
                            minLength="2"
                            maxLength="100"
                            aria-required="true"
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="description">Description</label>
                        <textarea
                            id="description"
                            name="description"
                            value={formData.description}
                            onChange={handleInputChange}
                            maxLength="500"
                            rows="3"
                        />
                    </div>

                    <div className="form-group">
                        <label htmlFor="frequency">Frequency</label>
                        <select
                            id="frequency"
                            name="frequency"
                            value={formData.frequency}
                            onChange={handleInputChange}
                        >
                            <option value="daily">Daily</option>
                            <option value="weekly">Weekly</option>
                            <option value="monthly">Monthly</option>
                        </select>
                    </div>

                    <div className="form-group">
                        <label htmlFor="targetCount">Target Count</label>
                        <input
                            type="number"
                            id="targetCount"
                            name="targetCount"
                            value={formData.targetCount}
                            onChange={handleInputChange}
                            min="1"
                        />
                    </div>

                    <div className="form-group checkbox">
                        <label htmlFor="isActive">
                            <input
                                type="checkbox"
                                id="isActive"
                                name="isActive"
                                checked={formData.isActive}
                                onChange={handleInputChange}
                            />
                            Active
                        </label>
                    </div>

                    <div className="form-actions">
                        <button type="submit" className="btn-primary">
                            {editingHabit ? 'Update' : 'Create'}
                        </button>
                        <button type="button" onClick={resetForm} className="btn-secondary">
                            Cancel
                        </button>
                    </div>
                </form>
            )}

            <main className="habits-grid">
                {habits.length === 0 ? (
                    <p className="no-habits">No habits yet. Create your first habit to get started!</p>
                ) : (
                    habits.map(habit => (
                        <article key={habit.id} className="habit-card">
                            <header>
                                <h3>{habit.name}</h3>
                                <span className={`badge ${habit.isActive ? 'active' : 'inactive'}`}>
                                    {habit.isActive ? 'Active' : 'Inactive'}
                                </span>
                            </header>
                            {habit.description && <p>{habit.description}</p>}
                            <div className="habit-details">
                                <span>Frequency: {habit.frequency}</span>
                                <span>Target: {habit.targetCount}x</span>
                            </div>
                            <footer className="habit-actions">
                                <button 
                                    onClick={() => toggleCompletion(habit.id)}
                                    className={completedToday[habit.id] ? "btn-success" : "btn-primary"}
                                    disabled={completedToday[habit.id]}
                                    aria-label={`Mark ${habit.name} as complete for today`}
                                >
                                    {completedToday[habit.id] ? "✓ Completed" : "Done Today?"}
                                </button>
                                <button 
                                    onClick={() => handleEdit(habit)}
                                    className="btn-secondary"
                                    aria-label={`Edit ${habit.name}`}
                                >
                                    Edit
                                </button>
                                <button 
                                    onClick={() => handleDelete(habit.id)}
                                    className="btn-danger"
                                    aria-label={`Delete ${habit.name}`}
                                >
                                    Delete
                                </button>
                            </footer>
                        </article>
                    ))
                )}
            </main>
                </div>

                <aside className="habit-sidebar">
                    <DailyTracker refreshTrigger={refreshTrigger} />
                </aside>
            </div>
        </div>
    );
};

export default HabitList;
