// Generated by GitHub Copilot
import React from 'react';
import { Link } from 'react-router-dom';
import '../styles/Navbar.css';

/**
 * Navigation bar component for the application.
 * Accessible: Uses semantic nav element and keyboard navigation.
 * Provides consistent navigation across different screens.
 */
const Navbar = () => {
    return (
        <nav className="navbar" role="navigation" aria-label="Main navigation">
            <div className="navbar-container">
                <div className="navbar-brand">
                    <Link to="/" className="navbar-logo">
                        <h1>Habits Tracker</h1>
                    </Link>
                </div>
                
                <ul className="navbar-menu">
                    <li className="navbar-item">
                        <Link to="/" className="navbar-link" aria-label="Go to My Habits page">
                            My Habits
                        </Link>
                    </li>
                    <li className="navbar-item">
                        <Link to="/calendar" className="navbar-link" aria-label="Go to Calendar page">
                            Calendar
                        </Link>
                    </li>
                    <li className="navbar-item">
                        <Link to="/statistics" className="navbar-link" aria-label="Go to Statistics page">
                            Statistics
                        </Link>
                    </li>
                </ul>
            </div>
        </nav>
    );
};

export default Navbar;
