// Generated by GitHub Copilot
package com.habittracker.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Entity representing the split "Need" vs "Want" expense recorded for a single day,
 * including the categories the "Want" portion was spent on.
 */
@Entity
@Table(name = "daily_expenses")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DailyExpense {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "entry_date", nullable = false, unique = true)
    private LocalDate entryDate;

    @Column(name = "need_amount", nullable = false)
    private Double needAmount = 0.0;

    @Column(name = "want_amount", nullable = false)
    private Double wantAmount = 0.0;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "daily_expense_want_categories", joinColumns = @JoinColumn(name = "daily_expense_id"))
    @Column(name = "category")
    private List<String> wantCategories = new ArrayList<>();

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (entryDate == null) {
            entryDate = LocalDate.now();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
