// Generated by GitHub Copilot
package com.habittracker.repository;

import com.habittracker.entity.DailyExpense;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for DailyExpense entity operations.
 * Provides database access methods for daily need/want expense tracking.
 */
@Repository
public interface DailyExpenseRepository extends JpaRepository<DailyExpense, Long> {

    /**
     * Find the expense record for a specific date.
     * @param entryDate The entry date
     * @return Optional containing the expense record if found
     */
    Optional<DailyExpense> findByEntryDate(LocalDate entryDate);

    /**
     * Find expense records within a date range.
     * @param startDate Start date
     * @param endDate End date
     * @return List of expense records
     */
    List<DailyExpense> findByEntryDateBetween(LocalDate startDate, LocalDate endDate);
}
