// Generated by GitHub Copilot
package com.habittracker.repository;

import com.habittracker.entity.Habit;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Repository interface for Habit entity operations.
 * Provides database access methods for habit management.
 */
@Repository
public interface HabitRepository extends JpaRepository<Habit, Long> {
    
    /**
     * Find all active habits.
     * @return List of active habits
     */
    List<Habit> findByIsActiveTrue();
    
    /**
     * Find habits by name containing the search term (case-insensitive).
     * @param name Search term
     * @return List of matching habits
     */
    List<Habit> findByNameContainingIgnoreCase(String name);
}
