// Generated by GitHub Copilot
package com.habittracker.repository;

import com.habittracker.entity.HabitEntry;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for HabitEntry entity operations.
 * Provides database access methods for habit entry tracking.
 */
@Repository
public interface HabitEntryRepository extends JpaRepository<HabitEntry, Long> {
    
    /**
     * Find all entries for a specific habit.
     * @param habitId The habit ID
     * @return List of habit entries
     */
    List<HabitEntry> findByHabitId(Long habitId);
    
    /**
     * Find entries for a habit within a date range.
     * @param habitId The habit ID
     * @param startDate Start date
     * @param endDate End date
     * @return List of habit entries
     */
    List<HabitEntry> findByHabitIdAndEntryDateBetween(Long habitId, LocalDate startDate, LocalDate endDate);
    
    /**
     * Find a specific habit entry by habit ID and date.
     * @param habitId The habit ID
     * @param entryDate The entry date
     * @return Optional containing the entry if found
     */
    Optional<HabitEntry> findByHabitIdAndEntryDate(Long habitId, LocalDate entryDate);
}
