/* Generated by GitHub Copilot */
import axios from 'axios';

const API_BASE_URL = process.env.REACT_APP_API_URL;

/**
 * API service for daily expense management.
 * Handles the Need/Want split expense tracking, backed by the database
 * so data is available across browsers/devices, unlike localStorage.
 */
class ExpenseService {

    /**
     * Get the expense record for a specific date.
     * @param {string} date - Date (YYYY-MM-DD)
     * @returns {Promise} Promise with the expense record (204 if none exists)
     */
    getByDate(date) {
        return axios.get(`${API_BASE_URL}/expenses/date/${date}`);
    }

    /**
     * Get expense records within a date range.
     * @param {string} startDate - Start date (YYYY-MM-DD)
     * @param {string} endDate - End date (YYYY-MM-DD)
     * @returns {Promise} Promise with the list of expense records
     */
    getByDateRange(startDate, endDate) {
        return axios.get(`${API_BASE_URL}/expenses/range`, {
            params: { startDate, endDate }
        });
    }

    /**
     * Create or update the expense record for a date.
     * @param {Object} expenseData - { entryDate, needAmount, wantAmount, wantCategories }
     * @returns {Promise} Promise with the created/updated expense record
     */
    createOrUpdateExpense(expenseData) {
        return axios.post(`${API_BASE_URL}/expenses`, expenseData);
    }
}

export default new ExpenseService();
