/* Generated by GitHub Copilot */
import axios from 'axios';

// For mobile access, use your PC's IP address
// For local development only, use http://localhost:8080/api
const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://192.168.1.10:8080/api';

/**
 * API service for habit entry management.
 * Handles tracking habit completions.
 */
class HabitEntryService {
    
    /**
     * Get all entries for a specific habit.
     * @param {number} habitId - The habit ID
     * @returns {Promise} Promise with habit entries
     */
    getEntriesByHabitId(habitId) {
        return axios.get(`${API_BASE_URL}/entries/habit/${habitId}`);
    }

    /**
     * Get entries for a habit within a date range.
     * @param {number} habitId - The habit ID
     * @param {string} startDate - Start date (YYYY-MM-DD)
     * @param {string} endDate - End date (YYYY-MM-DD)
     * @returns {Promise} Promise with filtered entries
     */
    getEntriesByDateRange(habitId, startDate, endDate) {
        return axios.get(`${API_BASE_URL}/entries/habit/${habitId}/range`, {
            params: { startDate, endDate }
        });
    }

    /**
     * Create or update a habit entry.
     * @param {Object} entryData - The entry data
     * @returns {Promise} Promise with created/updated entry
     */
    createOrUpdateEntry(entryData) {
        return axios.post(`${API_BASE_URL}/entries`, entryData);
    }

    /**
     * Delete a habit entry.
     * @param {number} id - The entry ID
     * @returns {Promise} Promise with delete confirmation
     */
    deleteEntry(id) {
        return axios.delete(`${API_BASE_URL}/entries/${id}`);
    }
}

export default new HabitEntryService();
