/* Generated by GitHub Copilot */
import axios from 'axios';

// For mobile access, use your PC's IP address
// For local development only, use http://localhost:8080/api
const API_BASE_URL = process.env.REACT_APP_API_BASE_URL || 'http://localhost:8080/api';

/**
 * API service for habit management.
 * Handles all HTTP requests to the backend API.
 */
class HabitService {
    
    /**
     * Get all habits.
     * @returns {Promise} Promise with habits data
     */
    getAllHabits() {
        return axios.get(`${API_BASE_URL}/habits`);
    }

    /**
     * Get all active habits.
     * @returns {Promise} Promise with active habits data
     */
    getActiveHabits() {
        return axios.get(`${API_BASE_URL}/habits/active`);
    }

    /**
     * Get a habit by ID.
     * @param {number} id - The habit ID
     * @returns {Promise} Promise with habit data
     */
    getHabitById(id) {
        return axios.get(`${API_BASE_URL}/habits/${id}`);
    }

    /**
     * Create a new habit.
     * @param {Object} habitData - The habit data
     * @returns {Promise} Promise with created habit
     */
    createHabit(habitData) {
        return axios.post(`${API_BASE_URL}/habits`, habitData);
    }

    /**
     * Update an existing habit.
     * @param {number} id - The habit ID
     * @param {Object} habitData - The updated habit data
     * @returns {Promise} Promise with updated habit
     */
    updateHabit(id, habitData) {
        return axios.put(`${API_BASE_URL}/habits/${id}`, habitData);
    }

    /**
     * Delete a habit.
     * @param {number} id - The habit ID
     * @returns {Promise} Promise with delete confirmation
     */
    deleteHabit(id) {
        return axios.delete(`${API_BASE_URL}/habits/${id}`);
    }

    /**
     * Search habits by name.
     * @param {string} name - Search term
     * @returns {Promise} Promise with matching habits
     */
    searchHabits(name) {
        return axios.get(`${API_BASE_URL}/habits/search`, {
            params: { name }
        });
    }
}

export default new HabitService();
