/* Generated by GitHub Copilot */
import React from 'react';
import HabitList from './components/HabitList';
import './styles/App.css';

/**
 * Main App component.
 * Entry point for the Habits Tracker application.
 */
function App() {
  return (
    <div className="App">
      <HabitList />
    </div>
  );
}

export default App;
