/* Generated by GitHub Copilot */
import React from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Navbar from './components/Navbar';
import HabitList from './components/HabitList';
import './styles/App.css';

/**
 * Main App component.
 * Entry point for the Habits Tracker application.
 * Uses React Router for navigation between different screens.
 */
function App() {
  return (
    <Router>
      <div className="App">
        <Navbar />
        <main className="main-content">
          <Routes>
            <Route path="/" element={<HabitList />} />
            <Route path="/calendar" element={<div className="placeholder-page"><h2>Calendar View</h2><p>Coming soon...</p></div>} />
            <Route path="/statistics" element={<div className="placeholder-page"><h2>Statistics</h2><p>Coming soon...</p></div>} />
          </Routes>
        </main>
      </div>
    </Router>
  );
}

export default App;
