// Generated by GitHub Copilot
package com.habittracker.controller;

import com.habittracker.dto.DailyExpenseDTO;
import com.habittracker.entity.DailyExpense;
import com.habittracker.service.DailyExpenseService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

/**
 * REST Controller for Daily Expense management.
 * Provides endpoints for tracking the Need/Want split of a day's expenses.
 * Security: Input validation via @Valid annotations.
 */
@RestController
@RequestMapping("/api/expenses")
@CrossOrigin(origins = "${cors.allowed.origins}")
public class DailyExpenseController {

    @Autowired
    private DailyExpenseService dailyExpenseService;

    /**
     * Get the expense record for a specific date.
     * @param date The date (format: yyyy-MM-dd)
     * @return The expense record, or 204 if none exists for that date
     */
    @GetMapping("/date/{date}")
    public ResponseEntity<DailyExpense> getByDate(
            @PathVariable @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate date) {
        DailyExpense expense = dailyExpenseService.getByDate(date);
        return expense != null ? ResponseEntity.ok(expense) : ResponseEntity.noContent().build();
    }

    /**
     * Get expense records within a date range.
     * @param startDate Start date (format: yyyy-MM-dd)
     * @param endDate End date (format: yyyy-MM-dd)
     * @return List of expense records
     */
    @GetMapping("/range")
    public ResponseEntity<List<DailyExpense>> getByDateRange(
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate) {
        return ResponseEntity.ok(dailyExpenseService.getByDateRange(startDate, endDate));
    }

    /**
     * Create or update the expense record for a date.
     * Security: Input validation performed via @Valid.
     * @param dailyExpenseDTO The expense data
     * @return The created or updated expense record
     */
    @PostMapping
    public ResponseEntity<DailyExpense> createOrUpdateExpense(@Valid @RequestBody DailyExpenseDTO dailyExpenseDTO) {
        DailyExpense expense = dailyExpenseService.createOrUpdateExpense(dailyExpenseDTO);
        return ResponseEntity.status(HttpStatus.CREATED).body(expense);
    }
}
