// Generated by GitHub Copilot
package com.habittracker.controller;

import com.habittracker.dto.HabitEntryDTO;
import com.habittracker.entity.HabitEntry;
import com.habittracker.service.HabitEntryService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;

/**
 * REST Controller for Habit Entry management.
 * Provides endpoints for tracking habit completions.
 * Security: Input validation via @Valid annotations.
 */
@RestController
@RequestMapping("/api/entries")
@CrossOrigin(origins = "${cors.allowed.origins}")
public class HabitEntryController {

    @Autowired
    private HabitEntryService habitEntryService;

    /**
     * Get all entries for a specific habit.
     * @param habitId The habit ID
     * @return List of habit entries
     */
    @GetMapping("/habit/{habitId}")
    public ResponseEntity<List<HabitEntry>> getEntriesByHabitId(@PathVariable Long habitId) {
        return ResponseEntity.ok(habitEntryService.getEntriesByHabitId(habitId));
    }

    /**
     * Get entries for a habit within a date range.
     * @param habitId The habit ID
     * @param startDate Start date (format: yyyy-MM-dd)
     * @param endDate End date (format: yyyy-MM-dd)
     * @return List of habit entries
     */
    @GetMapping("/habit/{habitId}/range")
    public ResponseEntity<List<HabitEntry>> getEntriesByDateRange(
            @PathVariable Long habitId,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
            @RequestParam @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate) {
        return ResponseEntity.ok(habitEntryService.getEntriesByDateRange(habitId, startDate, endDate));
    }

    /**
     * Create or update a habit entry.
     * Security: Input validation performed via @Valid.
     * @param habitEntryDTO The entry data
     * @return The created or updated entry
     */
    @PostMapping
    public ResponseEntity<HabitEntry> createOrUpdateEntry(@Valid @RequestBody HabitEntryDTO habitEntryDTO) {
        HabitEntry entry = habitEntryService.createOrUpdateEntry(habitEntryDTO);
        return ResponseEntity.status(HttpStatus.CREATED).body(entry);
    }

    /**
     * Delete a habit entry.
     * @param id The entry ID
     * @return No content response
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteEntry(@PathVariable Long id) {
        habitEntryService.deleteEntry(id);
        return ResponseEntity.noContent().build();
    }
}
