// Generated by GitHub Copilot
package com.habittracker.controller;

import com.habittracker.dto.HabitDTO;
import com.habittracker.entity.Habit;
import com.habittracker.service.HabitService;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST Controller for Habit management.
 * Provides endpoints for CRUD operations on habits.
 * Security: Input validation via @Valid annotations.
 */
@RestController
@RequestMapping("/api/habits")
@CrossOrigin(origins = "${cors.allowed.origins}")
public class HabitController {

    @Autowired
    private HabitService habitService;

    /**
     * Get all habits.
     * @return List of all habits
     */
    @GetMapping
    public ResponseEntity<List<Habit>> getAllHabits() {
        return ResponseEntity.ok(habitService.getAllHabits());
    }

    /**
     * Get all active habits.
     * @return List of active habits
     */
    @GetMapping("/active")
    public ResponseEntity<List<Habit>> getActiveHabits() {
        return ResponseEntity.ok(habitService.getActiveHabits());
    }

    /**
     * Get a habit by ID.
     * @param id The habit ID
     * @return The habit
     */
    @GetMapping("/{id}")
    public ResponseEntity<Habit> getHabitById(@PathVariable Long id) {
        return ResponseEntity.ok(habitService.getHabitById(id));
    }

    /**
     * Create a new habit.
     * Security: Input validation performed via @Valid.
     * @param habitDTO The habit data
     * @return The created habit
     */
    @PostMapping
    public ResponseEntity<Habit> createHabit(@Valid @RequestBody HabitDTO habitDTO) {
        Habit createdHabit = habitService.createHabit(habitDTO);
        return ResponseEntity.status(HttpStatus.CREATED).body(createdHabit);
    }

    /**
     * Update an existing habit.
     * Security: Input validation performed via @Valid.
     * @param id The habit ID
     * @param habitDTO The updated habit data
     * @return The updated habit
     */
    @PutMapping("/{id}")
    public ResponseEntity<Habit> updateHabit(@PathVariable Long id, @Valid @RequestBody HabitDTO habitDTO) {
        Habit updatedHabit = habitService.updateHabit(id, habitDTO);
        return ResponseEntity.ok(updatedHabit);
    }

    /**
     * Delete a habit.
     * @param id The habit ID
     * @return No content response
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteHabit(@PathVariable Long id) {
        habitService.deleteHabit(id);
        return ResponseEntity.noContent().build();
    }

    /**
     * Search habits by name.
     * @param name Search term
     * @return List of matching habits
     */
    @GetMapping("/search")
    public ResponseEntity<List<Habit>> searchHabits(@RequestParam String name) {
        return ResponseEntity.ok(habitService.searchHabitsByName(name));
    }
}
