// Generated by GitHub Copilot
package com.habittracker;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Main application class for Habits Tracker backend.
 * Starts the Spring Boot application server.
 */
@SpringBootApplication
public class HabitsTrackerApplication {

    public static void main(String[] args) {
        SpringApplication.run(HabitsTrackerApplication.class, args);
    }
}
